### ISSUE TITLE
multi-resolutional process

### ISSUE THREAD

**Issue by tangzhy** [sunzewei2715/Doc2Doc_NMT#2]
Hi zewei,

We've come across your inspiring work of Doc2doc NMT.

Yet it remains unclear for me on how the data is preprocessed before fed into a classical seq2seq model. 

To my best understanding, for any paired documents (S, T), you seem performing the multi-resolutional process on both S and T? Namely, both the source document and target document are split into multiple segments, and then concatenated as the training inputs (S, T) for the NMT model? Or do you perform the multi-resolutional process on S only?

Thanks

**Comment by sunzewei2715** [comment]
> 

Yes, we perform the multi-resolutional process on both S and T

**Comment by tangzhy** [comment]
I wonder under this setting, how do you perform inference since the predicted T shall be like multi-resolved T?

Then you just directly stop decoding when hitting the EOS token?

Does it introduce some discrepancy between training and inference? Or maybe I was wrong in understanding this?

**Comment by xudekuan** [comment]
Great!!!

**Comment by xudekuan** [comment]
I understand that first we have a doc aligned corpus and then devided both S and T into several parts on the same scale and then put them into train. 
The problem that maybe discrapency between S and T but the system can learn from the corpus and self-adjust the model. so we can overlook the disrapency.
Is that the case?
Thanks.

**Comment by sunzewei2715** [comment]
> I wonder under this setting, how do you perform inference since the predicted T shall be like multi-resolved T? Or you just directly stop decoding when hitting the EOS token?
> 
> Does it introduce some discrepancy between training and inference? Maybe I was wrong in understanding this?

In the training, we simply use multi-resolutional S & T which are aligned. In the inference, we just infer the whole document.

For an example, we have Doc_x(s1, s2, s3, s4) and Doc_y(t1, t2, t3, t4), we train the model with:
(s1, t1), (s2, t2), (s3, t3), (s4, t4), (s1s2, t1t2), (s3s4, t3t4), (s1s2s3s4, t1t2t3t4)

When a new Doc_z comes (e.g. z1, z2, z3, z4), we input (z1, z2, z3, z4) into the model and obtain the final Document sequence.

**Comment by tangzhy** [comment]
Thanks, that's quite neat:)
