### ISSUE TITLE
篇章分句对齐问题

### ISSUE THREAD

**Issue by KindAdvisor** [sunzewei2715/Doc2Doc_NMT#6]
您好，在使用论文中数据处理方法，对篇章数据使用pragmatic_segmenter对双侧数据分句后，发现平行篇章数据双侧分句后不对齐：
使用篇章数据 : en.doc  zh.doc
经过pragmatic_segmenter后得到en.del  zh.del
统计同一篇章两侧句子数量，约80%数据不一致
想向您请教这边的处理方式。

**Comment by sunzewei2715** [comment]
> 您好，在使用论文中数据处理方法，对篇章数据使用pragmatic_segmenter对双侧数据分句后，发现平行篇章数据双侧分句后不对齐： 使用篇章数据 : en.doc zh.doc 经过pragmatic_segmenter后得到en.del zh.del 统计同一篇章两侧句子数量，约80%数据不一致 想向您请教这边的处理方式。

有已经处理好的数据：zh.del en.del，可以直接使用~

**Comment by KindAdvisor** [comment]
> > 您好，在使用论文中数据处理方法，对篇章数据使用pragmatic_segmenter对双侧数据分句后，发现平行篇章数据双侧分句后不对齐： 使用篇章数据 : en.doc zh.doc 经过pragmatic_segmenter后得到en.del zh.del 统计同一篇章两侧句子数量，约80%数据不一致 想向您请教这边的处理方式。
> 
> 有已经处理好的数据：zh.del en.del，可以直接使用~

感谢你的回答，有注意到这边不同类型数据的分布，因为本身DNMT数据比较少，参考论文方法做了同源的扩充。
想复现一下这边对齐的过程，做一些数据上的扩充，但是卡在了篇章分割句子后对齐的问题上。

**Comment by sunzewei2715** [comment]
> > > 您好，在使用论文中数据处理方法，对篇章数据使用pragmatic_segmenter对双侧数据分句后，发现平行篇章数据双侧分句后不对齐： 使用篇章数据 : en.doc zh.doc 经过pragmatic_segmenter后得到en.del zh.del 统计同一篇章两侧句子数量，约80%数据不一致 想向您请教这边的处理方式。
> > 
> > 
> > 有已经处理好的数据：zh.del en.del，可以直接使用~
> 
> 感谢你的回答，有注意到这边不同类型数据的分布，因为本身DNMT数据比较少，参考论文方法做了同源的扩充。 想复现一下这边对齐的过程，做一些数据上的扩充，但是卡在了篇章分割句子后对齐的问题上。

对，所以当初我们选的就是那种分栏对齐的双语网站，对齐度较高。而且即使这样，经过清洗，也有很大一部分被筛选掉了。普通的文档数据应该很难对齐。

**Comment by fengsxy** [comment]
如果篇章数据不对齐的话，那么测试数据如何和对比模型保持一致呢？
其次是能否根据句子数量差异性大小改变句子的多分辨率？例如这篇文章是120句那篇文章是130句，那我的颗粒度划分最多可以划到120/2=60 130/2=65，则不进行细分，有一个动态的策略
