### ISSUE TITLE
d-BleU和s-BleU的脚本可否分享一下吗？

### ISSUE THREAD

**Issue by robotsp** [sunzewei2715/Doc2Doc_NMT#7]
如题 @sunzewei2715 

谢谢！

**Comment by sunzewei2715** [comment]
就普通的bleu脚本：https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl

**Comment by sunzewei2715** [comment]
> 如题 @sunzewei2715
> 
> 谢谢！

就普通的bleu脚本：https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl

**Comment by sunzewei2715** [comment]
> 如题 @sunzewei2715
> 
> 谢谢！

就普通的bleu脚本：https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl

s-BLEU和d-BLEU的区别只是拿sentence算还是拿document算而已

PS：是lower-case的BLEU

**Comment by robotsp** [comment]
OK, 谢谢！
