### ISSUE TITLE
关于transformer-base的encoder输入长度

### ISSUE THREAD

**Issue by LYH6645** [sunzewei2715/Doc2Doc_NMT#9]
在实验中，我发现transformer-base的encoder输入长度被限制在512个tokens以内，我想知道在您的实验中是否对超出512的序列进行了截断或者使用了其他方法？

**Comment by sunzewei2715** [comment]
> 在实验中，我发现transformer-base的encoder输入长度被限制在512个tokens以内，我想知道在您的实验中是否对超出512的序列进行了截断或者使用了其他方法？

我们没有做截断。如果担心的是positional embedding，我们采用的是transformer原始论文中的三角函数，对长度没有限制～

**Comment by RedSky-allbreak** [comment]
> 

方便提供一下fairseq transformer的参数设定shell指令么，类似于fairseq-train --a A --b B...
